# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create!(first_name: "Mike-the-Admin", last_name: "Silb", email: "ms@email.com", password: "123456", role: "admin")
User.create!(first_name: "Jack" , last_name: "Nicholson", email: "jn@email.com", password: "123456")
User.create!(first_name: "Diane" , last_name: "Cannon", email: "dc@email.com", password: "123456")
User.create!(first_name: "Mark" , last_name: "Wahlberg", email: "mw@email.com", password: "123456")
User.create!(first_name: "Ben" , last_name: "Affleck", email: "ba@email.com", password: "123456")
Nbafinal.create!(year: 1959, champion: "Celtics", numgames: 4)
Nbafinal.create!(year: 1962, champion: "Celtics", numgames: 7)
Nbafinal.create!(year: 1963, champion: "Celtics", numgames: 6)
Nbafinal.create!(year: 1965, champion: "Celtics", numgames: 5)
Nbafinal.create!(year: 1966, champion: "Celtics", numgames: 7)
Nbafinal.create!(year: 1968, champion: "Celtics", numgames: 6)
Nbafinal.create!(year: 1969, champion: "Celtics", numgames: 7, mvp: "Jerry West")
Nbafinal.create!(year: 1984, champion: "Celtics", numgames: 7, mvp: "Larry Bird")
Nbafinal.create!(year: 1985, champion: "Lakers", numgames: 6, mvp: "Kareem Abdul-Jabbar")
Nbafinal.create!(year: 1987, champion: "Lakers", numgames: 6, mvp: "Magic Johnson")
Nbafinal.create!(year: 2008, champion: "Celtics", numgames: 6, mvp: "Paul Pierce")
Nbafinal.create!(year: 2010, champion: "Lakers", numgames: 7, mvp: "Kobe Bryant")
Game.create!(date: '2010-06-03', score: "Celtics 89, Lakers 102", nbafinal_id: 14)
Game.create!(date: '2010-06-06', score: "Celtics 103, Lakers 94", nbafinal_id: 14)
Game.create!(date: '2010-06-08', score: "Lakers 91, Celtics 84", nbafinal_id: 14)
Game.create!(date: '2010-06-10', score: "Lakers 89, Celtics 96", nbafinal_id: 14)
Game.create!(date: '2010-06-13', score: "Lakers 86, Celtics 92", nbafinal_id: 14)
Game.create!(date: '2010-06-15', score: "Celtics 67, Lakers 89", nbafinal_id: 14)
Game.create!(date: '2010-06-17', score: "Celtics 79, Lakers 83", nbafinal_id: 14)
Game.create!(date: '2008-06-05', score: "Lakers 88, Celtics 98", nbafinal_id: 11)
Game.create!(date: '2008-06-08', score: "Lakers 102, Celtics 108", nbafinal_id: 11)
Game.create!(date: '2008-06-10', score: "Celtics 81, Lakers 87", nbafinal_id: 11)
Game.create!(date: '2008-06-12', score: "Celtics 97, Lakers 91", nbafinal_id: 11)
Game.create!(date: '2008-06-15', score: "Celtics 98, Lakers 103", nbafinal_id: 11)
Game.create!(date: '2008-06-17', score: "Lakers 92, Celtics 131", nbafinal_id: 11)
Team.create!(teamname: "Lakers", nbafinal_id: 14)
Team.create!(teamname: "Celtics", nbafinal_id: 14)
Team.create!(teamname: "Lakers", nbafinal_id: 11)
Team.create!(teamname: "Celtics", nbafinal_id: 11)
Team.create!(teamname: "Lakers", nbafinal_id: 10)
Team.create!(teamname: "Celtics", nbafinal_id: 10)
Team.create!(teamname: "Lakers", nbafinal_id: 9)
Team.create!(teamname: "Celtics", nbafinal_id: 9)
Team.create!(teamname: "Lakers", nbafinal_id: 8)
Team.create!(teamname: "Celtics", nbafinal_id: 8)
Team.create!(teamname: "Lakers", nbafinal_id: 7)
Team.create!(teamname: "Celtics", nbafinal_id: 7)
Team.create!(teamname: "Lakers", nbafinal_id: 6)
Team.create!(teamname: "Celtics", nbafinal_id: 6)
Team.create!(teamname: "Lakers", nbafinal_id: 5)
Team.create!(teamname: "Celtics", nbafinal_id: 5)
Team.create!(teamname: "Lakers", nbafinal_id: 4)
Team.create!(teamname: "Celtics", nbafinal_id: 4)
Team.create!(teamname: "Lakers", nbafinal_id: 3)
Team.create!(teamname: "Celtics", nbafinal_id: 3)
Team.create!(teamname: "Lakers", nbafinal_id: 2)
Team.create!(teamname: "Celtics", nbafinal_id: 2)
Team.create!(teamname: "Lakers", nbafinal_id: 1)
Team.create!(teamname: "Celtics", nbafinal_id: 1)
